### ISSUE TITLE
Example site down?

### ISSUE THREAD

**Issue by OliverM** [cjohansen/cjohansen-no#2]
Hi Christian,

Just a quick note to say cjohansen.no seems to be down at the moment - the guide to Stasis was something I found really useful, thanks! I'm just letting you know here instead of the absent site.

**Comment by cjohansen** [comment]
My server provider had a RAID crash, and I suffered data loss. I've not yet had the time or energy to piece things back together. It'll be back up eventually.

**Comment by OliverM** [comment]
Sounds like a ton of hassle. I’m not in dire need in any way. Sorry to hear that though, the article was very good!

**Comment by cjohansen** [comment]
Thanks! In case you need to refer to it or whatever, I put it in a gist while I wait to find time and energy to put the site back up: https://gist.github.com/cjohansen/45b73e6206597c51b1dc

**Comment by OliverM** [comment]
Thank you!
